### ISSUE TITLE
UWP style not working, and Android Menu are not shown.

### ISSUE THREAD

**Issue by halitsavafoglu** [adamped/xarch-starter#4]
Hello,
i know that it's a demo, so every day there's a new update and you can't keep updating a demo, but trust me this demo is the best fit demo for me, so please can you fix these 2 issues.
- i tried to run the application on Xamarin Player (Android 6.0), after login page, the main page doesn't show the menu, and when i press on it's place the application closed by the os.
- for the UWP when i tried to run the application, the functionality are working just fine, but the menu items are not shown, and the application has no style like the Android version.
  Best Regards.

**Comment by zoemy** [comment]
Hi, This sample is really awesome but I'm not sure how to set the BindingContext of the MenuPage in the MainStack class. Could you give a hint?

**Comment by adamped** [comment]
@zoemy - You can just set it by creating a new ViewModel and doing BindingContext = new MyViewModel()

**Comment by zoemy** [comment]
I tried to do that but I get this exception:  
`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation`

This are the two ways I used. In both cases I get that exception.
```
  BindingContext = _pageService.GetBindingContext(typeof(MenuPage))
  BindingContext = new MenuViewModel(null, defaultMessenger,navigationService, dialogService) 
```

**Comment by adamped** [comment]
@zoemy - I just tested in UWP with a new MenuViewModel and it worked as expected.

I updated the repo, also to include the latest XF. Give that a try and let me know how you go.

Also this project is rather old, you may want to give Exrin a try. I built an entire framework which is maintained and supported. Have a look at https://github.com/exrin/Exrin. There are 2 sample projects, Exrin Sample (very quick and simple) and Tesla App (more complex with MasterDetailPages and TabbedPages)
